export { default as Home } from './Home'
export { default as Experience } from './Experience'
export { default as Projects } from './Projects'
export { default as Blogs } from './Blogs'
export { default as Contact } from './Contact'